admin:
  access_log_path: "/dev/null"
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

node:
  cluster: x-monitor-cluster
  id: x-monitor

dynamic_resources:
  cds_config:
    path: /home/calmwu/Program/cpp/x-monitor/env/config/proxy/x-monitor-envoy-cds.yaml
  lds_config:
    path: /home/calmwu/Program/cpp/x-monitor/env/config/proxy/x-monitor-envoy-lds.yaml