{
 "title": "ebpf",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Host", "query": { "query": "label_values(instance)" } },
   {
    "name": "device",
    "label": "device",
    "query": {
     "query": "label_values(bio_request_total_kbytes,device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU schedule", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "cpu_schedule_runq_latency_bucket",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "cpu_schedule_runq_latency_bucket{instance=~\"$instance.*\",le!=\"+Inf\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "cpu_schedule_offcpu_duration",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "cpu_schedule_offcpu_duration{instance=~\"$instance.*\"}",
     "legendFormat": "{{pid}}"
    }
   ]
  },
  { "title": "BIO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "bio_request_in2c_latency_bucket read",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "bio_request_in2c_latency_bucket{instance=~\"$instance.*\",device=\"$device\", operation=\"read\", le!=\"+Inf\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "bio_request_in2c_latency_bucket write",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "bio_request_in2c_latency_bucket{instance=~\"$instance.*\",device=\"$device\", operation=\"write\", le!=\"+Inf\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "bio_request_in2c_latency_bucket flush",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "bio_request_in2c_latency_bucket{instance=~\"$instance.*\",device=\"$device\", operation=\"flush\", le!=\"+Inf\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "bio_request_is2c_latency_bucket read",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "bio_request_is2c_latency_bucket{instance=~\"$instance.*\",device=\"$device\", operation=\"read\", le!=\"+Inf\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "bio_request_is2c_latency_bucket write",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "bio_request_is2c_latency_bucket{instance=~\"$instance.*\",device=\"$device\", operation=\"write\", le!=\"+Inf\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "bio_request_is2c_latency_bucket flush",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "bio_request_is2c_latency_bucket{instance=~\"$instance.*\",device=\"$device\", operation=\"flush\", le!=\"+Inf\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "bio_request_ratio read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "bio_request_randomized_ratio{instance=~\"$instance.*\",device=\"$device\",operation=\"read\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "bio_request_sequential_ratio{instance=~\"$instance.*\",device=\"$device\",operation=\"read\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "bio_request_ratio write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "bio_request_randomized_ratio{instance=~\"$instance.*\",device=\"sda\",operation=\"write\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "bio_request_sequential_ratio{instance=~\"$instance.*\",device=\"sda\",operation=\"write\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "bio_request_ratio flush",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "bio_request_randomized_ratio{instance=~\"$instance.*\",device=\"$device\",operation=\"flush\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "bio_request_sequential_ratio{instance=~\"$instance.*\",device=\"$device\",operation=\"flush\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "bio_request_completed_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bio_request_completed_count{instance=~\"$instance.*\",operation=\"read\",device=\"$device\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "bio_request_completed_count{instance=~\"$instance.*\",operation=\"write\",device=\"$device\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "bio_request_completed_count{instance=~\"$instance.*\",operation=\"flush\",device=\"$device\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "PageCache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "PageCache Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "filesystem_pagecache_ratio{instance=~\"$instance.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "PageCacheOperateCount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "filesystem_pagecache_hits{instance=~\"$instance.*\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "filesystem_pagecache_misses{instance=~\"$instance.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "OOM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "oom_kill_memcg",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "oom_kill_memcg{instance=~\"$instance.*\"}",
     "legendFormat": "{{pid}}"
    }
   ]
  }
 ]
}