// Code generated by "stringer -type=EBPFEventType -output=event_type_string.go"; DO NOT EDIT.

package eventcenter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EBPF_EVENT_NONE-0]
	_ = x[EBPF_EVENT_PROCESS_EXIT-1]
}

const _eBPFEventType_name = "EBPF_EVENT_NONEEBPF_EVENT_PROCESS_EXIT"

var _eBPFEventType_index = [...]uint8{0, 15, 38}

func (i EBPFEventType) String() string {
	if i >= EBPFEventType(len(_eBPFEventType_index)-1) {
		return "EBPFEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _eBPFEventType_name[_eBPFEventType_index[i]:_eBPFEventType_index[i+1]]
}
