/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED! */
#ifndef __XM_RUNQLAT_BPF_SKEL_H__
#define __XM_RUNQLAT_BPF_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

struct xm_runqlat_bpf {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_program *xm_btp_sched_wakeup;
		struct bpf_program *xm_btp_sched_wakeup_new;
		struct bpf_program *xm_btp_sched_switch;
	} progs;
	struct {
		struct bpf_link *xm_btp_sched_wakeup;
		struct bpf_link *xm_btp_sched_wakeup_new;
		struct bpf_link *xm_btp_sched_switch;
	} links;
};

static void
xm_runqlat_bpf__destroy(struct xm_runqlat_bpf *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
xm_runqlat_bpf__create_skeleton(struct xm_runqlat_bpf *obj);

static inline struct xm_runqlat_bpf *
xm_runqlat_bpf__open_opts(const struct bpf_object_open_opts *opts)
{
	struct xm_runqlat_bpf *obj;
	int err;

	obj = (struct xm_runqlat_bpf *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = xm_runqlat_bpf__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	xm_runqlat_bpf__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct xm_runqlat_bpf *
xm_runqlat_bpf__open(void)
{
	return xm_runqlat_bpf__open_opts(NULL);
}

static inline int
xm_runqlat_bpf__load(struct xm_runqlat_bpf *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct xm_runqlat_bpf *
xm_runqlat_bpf__open_and_load(void)
{
	struct xm_runqlat_bpf *obj;
	int err;

	obj = xm_runqlat_bpf__open();
	if (!obj)
		return NULL;
	err = xm_runqlat_bpf__load(obj);
	if (err) {
		xm_runqlat_bpf__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
xm_runqlat_bpf__attach(struct xm_runqlat_bpf *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
xm_runqlat_bpf__detach(struct xm_runqlat_bpf *obj)
{
	return bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *xm_runqlat_bpf__elf_bytes(size_t *sz);

static inline int
xm_runqlat_bpf__create_skeleton(struct xm_runqlat_bpf *obj)
{
	struct bpf_object_skeleton *s;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)
		goto err;

	s->sz = sizeof(*s);
	s->name = "xm_runqlat_bpf";
	s->obj = &obj->obj;

	/* programs */
	s->prog_cnt = 3;
	s->prog_skel_sz = sizeof(*s->progs);
	s->progs = (struct bpf_prog_skeleton *)calloc(s->prog_cnt, s->prog_skel_sz);
	if (!s->progs)
		goto err;

	s->progs[0].name = "xm_btp_sched_wakeup";
	s->progs[0].prog = &obj->progs.xm_btp_sched_wakeup;
	s->progs[0].link = &obj->links.xm_btp_sched_wakeup;

	s->progs[1].name = "xm_btp_sched_wakeup_new";
	s->progs[1].prog = &obj->progs.xm_btp_sched_wakeup_new;
	s->progs[1].link = &obj->links.xm_btp_sched_wakeup_new;

	s->progs[2].name = "xm_btp_sched_switch";
	s->progs[2].prog = &obj->progs.xm_btp_sched_switch;
	s->progs[2].link = &obj->links.xm_btp_sched_switch;

	s->data = (void *)xm_runqlat_bpf__elf_bytes(&s->data_sz);

	obj->skeleton = s;
	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return -ENOMEM;
}

static inline const void *xm_runqlat_bpf__elf_bytes(size_t *sz)
{
	*sz = 2376;
	return (const void *)"\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x08\x06\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x0d\0\
\x0c\0\xb7\0\0\0\0\0\0\0\x95\0\0\0\0\0\0\0\xb7\0\0\0\0\0\0\0\x95\0\0\0\0\0\0\0\
\xb7\0\0\0\0\0\0\0\x95\0\0\0\0\0\0\0\x44\x75\x61\x6c\x20\x42\x53\x44\x2f\x47\
\x50\x4c\0\x9f\xeb\x01\0\x18\0\0\0\0\0\0\0\xf8\0\0\0\xf8\0\0\0\xd7\x01\0\0\0\0\
\0\0\0\0\0\x02\x02\0\0\0\x01\0\0\0\0\0\0\x01\x08\0\0\0\x40\0\0\0\0\0\0\0\x01\0\
\0\x0d\x04\0\0\0\x18\0\0\0\x01\0\0\0\x1c\0\0\0\0\0\0\x08\x05\0\0\0\x22\0\0\0\0\
\0\0\x01\x04\0\0\0\x20\0\0\x01\x26\0\0\0\x01\0\0\x0c\x03\0\0\0\0\0\0\0\x01\0\0\
\x0d\x04\0\0\0\x18\0\0\0\x01\0\0\0\xd6\0\0\0\x01\0\0\x0c\x07\0\0\0\0\0\0\0\x01\
\0\0\x0d\x04\0\0\0\x18\0\0\0\x01\0\0\0\x48\x01\0\0\x01\0\0\x0c\x09\0\0\0\xae\
\x01\0\0\0\0\0\x01\x01\0\0\0\x08\0\0\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x0b\0\0\0\
\x0d\0\0\0\x0d\0\0\0\xb3\x01\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\xc7\x01\0\0\0\0\
\0\x0e\x0c\0\0\0\x01\0\0\0\xcf\x01\0\0\x01\0\0\x0f\0\0\0\0\x0e\0\0\0\0\0\0\0\
\x0d\0\0\0\0\x6c\x6f\x6e\x67\x20\x6c\x6f\x6e\x67\x20\x75\x6e\x73\x69\x67\x6e\
\x65\x64\x20\x69\x6e\x74\0\x63\x74\x78\0\x5f\x5f\x73\x33\x32\0\x69\x6e\x74\0\
\x78\x6d\x5f\x62\x74\x70\x5f\x73\x63\x68\x65\x64\x5f\x77\x61\x6b\x65\x75\x70\0\
\x74\x70\x5f\x62\x74\x66\x2f\x73\x63\x68\x65\x64\x5f\x77\x61\x6b\x65\x75\x70\0\
\x2f\x68\x6f\x6d\x65\x2f\x63\x61\x6c\x6d\x77\x75\x2f\x70\x72\x6f\x67\x72\x61\
\x6d\x2f\x63\x70\x70\x5f\x73\x70\x61\x63\x65\x2f\x78\x2d\x6d\x6f\x6e\x69\x74\
\x6f\x72\x2f\x70\x6c\x75\x67\x69\x6e\x5f\x65\x62\x70\x66\x2f\x62\x70\x66\x2f\
\x78\x6d\x5f\x72\x75\x6e\x71\x6c\x61\x74\x2e\x62\x70\x66\x2e\x63\0\x5f\x5f\x73\
\x33\x32\x20\x42\x50\x46\x5f\x50\x52\x4f\x47\x28\x78\x6d\x5f\x62\x74\x70\x5f\
\x73\x63\x68\x65\x64\x5f\x77\x61\x6b\x65\x75\x70\x2c\x20\x73\x74\x72\x75\x63\
\x74\x20\x74\x61\x73\x6b\x5f\x73\x74\x72\x75\x63\x74\x20\x2a\x74\x73\x29\x20\
\x7b\0\x78\x6d\x5f\x62\x74\x70\x5f\x73\x63\x68\x65\x64\x5f\x77\x61\x6b\x65\x75\
\x70\x5f\x6e\x65\x77\0\x74\x70\x5f\x62\x74\x66\x2f\x73\x63\x68\x65\x64\x5f\x77\
\x61\x6b\x65\x75\x70\x5f\x6e\x65\x77\0\x5f\x5f\x73\x33\x32\x20\x42\x50\x46\x5f\
\x50\x52\x4f\x47\x28\x78\x6d\x5f\x62\x74\x70\x5f\x73\x63\x68\x65\x64\x5f\x77\
\x61\x6b\x65\x75\x70\x5f\x6e\x65\x77\x2c\x20\x73\x74\x72\x75\x63\x74\x20\x74\
\x61\x73\x6b\x5f\x73\x74\x72\x75\x63\x74\x20\x2a\x74\x73\x29\x20\x7b\0\x78\x6d\
\x5f\x62\x74\x70\x5f\x73\x63\x68\x65\x64\x5f\x73\x77\x69\x74\x63\x68\0\x74\x70\
\x5f\x62\x74\x66\x2f\x73\x63\x68\x65\x64\x5f\x73\x77\x69\x74\x63\x68\0\x5f\x5f\
\x73\x33\x32\x20\x42\x50\x46\x5f\x50\x52\x4f\x47\x28\x78\x6d\x5f\x62\x74\x70\
\x5f\x73\x63\x68\x65\x64\x5f\x73\x77\x69\x74\x63\x68\x2c\x20\x73\x74\x72\x75\
\x63\x74\x20\x74\x61\x73\x6b\x5f\x73\x74\x72\x75\x63\x74\x20\x2a\x74\x73\x29\
\x20\x7b\0\x63\x68\x61\x72\0\x5f\x5f\x41\x52\x52\x41\x59\x5f\x53\x49\x5a\x45\
\x5f\x54\x59\x50\x45\x5f\x5f\0\x4c\x49\x43\x45\x4e\x53\x45\0\x6c\x69\x63\x65\
\x6e\x73\x65\0\x9f\xeb\x01\0\x20\0\0\0\0\0\0\0\x34\0\0\0\x34\0\0\0\x4c\0\0\0\
\x80\0\0\0\0\0\0\0\x08\0\0\0\x3a\0\0\0\x01\0\0\0\0\0\0\0\x06\0\0\0\xee\0\0\0\
\x01\0\0\0\0\0\0\0\x08\0\0\0\x5c\x01\0\0\x01\0\0\0\0\0\0\0\x0a\0\0\0\x10\0\0\0\
\x3a\0\0\0\x01\0\0\0\0\0\0\0\x4e\0\0\0\x98\0\0\0\x07\x4c\0\0\xee\0\0\0\x01\0\0\
\0\0\0\0\0\x4e\0\0\0\x06\x01\0\0\x07\x60\0\0\x5c\x01\0\0\x01\0\0\0\0\0\0\0\x4e\
\0\0\0\x70\x01\0\0\x07\x74\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\x03\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x03\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\x44\0\0\0\x12\0\x02\0\0\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x01\0\0\0\x12\
\0\x03\0\0\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x6c\0\0\0\x12\0\x04\0\0\0\0\0\0\0\0\
\0\x10\0\0\0\0\0\0\0\xc3\0\0\0\x11\0\x05\0\0\0\0\0\0\0\0\0\x0d\0\0\0\0\0\0\0\
\x08\x01\0\0\0\0\0\0\x04\0\0\0\x07\0\0\0\x2c\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\
\x3c\0\0\0\0\0\0\0\x04\0\0\0\x02\0\0\0\x4c\0\0\0\0\0\0\0\x04\0\0\0\x03\0\0\0\
\x60\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x78\0\0\0\0\0\0\0\x04\0\0\0\x02\0\0\0\
\x90\0\0\0\0\0\0\0\x04\0\0\0\x03\0\0\0\x0a\x0b\x0c\x0d\0\x78\x6d\x5f\x62\x74\
\x70\x5f\x73\x63\x68\x65\x64\x5f\x77\x61\x6b\x65\x75\x70\x5f\x6e\x65\x77\0\x74\
\x70\x5f\x62\x74\x66\x2f\x73\x63\x68\x65\x64\x5f\x77\x61\x6b\x65\x75\x70\x5f\
\x6e\x65\x77\0\x2e\x74\x65\x78\x74\0\x2e\x72\x65\x6c\x2e\x42\x54\x46\x2e\x65\
\x78\x74\0\x78\x6d\x5f\x62\x74\x70\x5f\x73\x63\x68\x65\x64\x5f\x77\x61\x6b\x65\
\x75\x70\0\x74\x70\x5f\x62\x74\x66\x2f\x73\x63\x68\x65\x64\x5f\x77\x61\x6b\x65\
\x75\x70\0\x78\x6d\x5f\x62\x74\x70\x5f\x73\x63\x68\x65\x64\x5f\x73\x77\x69\x74\
\x63\x68\0\x74\x70\x5f\x62\x74\x66\x2f\x73\x63\x68\x65\x64\x5f\x73\x77\x69\x74\
\x63\x68\0\x2e\x6c\x6c\x76\x6d\x5f\x61\x64\x64\x72\x73\x69\x67\0\x6c\x69\x63\
\x65\x6e\x73\x65\0\x2e\x73\x74\x72\x74\x61\x62\0\x2e\x73\x79\x6d\x74\x61\x62\0\
\x2e\x72\x65\x6c\x2e\x42\x54\x46\0\x4c\x49\x43\x45\x4e\x53\x45\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x31\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x58\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\
\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\x19\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x50\0\0\0\0\0\0\0\
\x10\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x80\0\0\0\
\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x60\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xa2\0\0\0\x01\0\0\0\x03\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x70\0\0\0\0\0\0\0\x0d\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xbe\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x7d\0\0\0\0\0\0\0\xe7\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x3b\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\
\x03\0\0\0\0\0\0\xa0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\xb2\0\0\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\x04\0\0\0\0\0\0\
\xc0\0\0\0\0\0\0\0\x0c\0\0\0\x04\0\0\0\x08\0\0\0\0\0\0\0\x18\0\0\0\0\0\0\0\xba\
\0\0\0\x09\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xc8\x04\0\0\0\0\0\0\x10\0\0\0\
\0\0\0\0\x08\0\0\0\x06\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x37\0\0\0\x09\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xd8\x04\0\0\0\0\0\0\x60\0\0\0\0\0\0\0\
\x08\0\0\0\x07\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x94\0\0\0\x03\x4c\xff\
\x6f\0\0\0\x80\0\0\0\0\0\0\0\0\0\0\0\0\x38\x05\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xaa\0\0\0\x03\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x3c\x05\0\0\0\0\0\0\xcb\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0";
}

#endif /* __XM_RUNQLAT_BPF_SKEL_H__ */
