// Code generated by "stringer -type=XMProcessVMMXmVmmEvtType -output=vmmevttype_string.go"; DO NOT EDIT.

package bpfmodule

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[XMProcessVMMXmVmmEvtTypeXM_VMM_EVT_TYPE_NONE-0]
	_ = x[XMProcessVMMXmVmmEvtTypeXM_VMM_EVT_TYPE_MMAP_ANON_PRIV-1]
	_ = x[XMProcessVMMXmVmmEvtTypeXM_VMM_EVT_TYPE_MMAP_SHARED-2]
	_ = x[XMProcessVMMXmVmmEvtTypeXM_VMM_EVT_TYPE_MMAP_OTHER-3]
	_ = x[XMProcessVMMXmVmmEvtTypeXM_VMM_EVT_TYPE_BRK-4]
}

const _XMProcessVMMXmVmmEvtType_name = "XMProcessVMMXmVmmEvtTypeXM_VMM_EVT_TYPE_NONEXMProcessVMMXmVmmEvtTypeXM_VMM_EVT_TYPE_MMAP_ANON_PRIVXMProcessVMMXmVmmEvtTypeXM_VMM_EVT_TYPE_MMAP_SHAREDXMProcessVMMXmVmmEvtTypeXM_VMM_EVT_TYPE_MMAP_OTHERXMProcessVMMXmVmmEvtTypeXM_VMM_EVT_TYPE_BRK"

var _XMProcessVMMXmVmmEvtType_index = [...]uint8{0, 44, 98, 149, 199, 242}

func (i XMProcessVMMXmVmmEvtType) String() string {
	if i >= XMProcessVMMXmVmmEvtType(len(_XMProcessVMMXmVmmEvtType_index)-1) {
		return "XMProcessVMMXmVmmEvtType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _XMProcessVMMXmVmmEvtType_name[_XMProcessVMMXmVmmEvtType_index[i]:_XMProcessVMMXmVmmEvtType_index[i+1]]
}
