// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64be || armbe || mips || mips64 || mips64p32 || ppc64 || s390 || s390x || sparc || sparc64
// +build arm64be armbe mips mips64 mips64p32 ppc64 s390 s390x sparc sparc64

package bpfmodule

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadXMProcessVM returns the embedded CollectionSpec for XMProcessVM.
func LoadXMProcessVM() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XMProcessVMBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load XMProcessVM: %w", err)
	}

	return spec, err
}

// LoadXMProcessVMObjects loads XMProcessVM and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*XMProcessVMObjects
//	*XMProcessVMPrograms
//	*XMProcessVMMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadXMProcessVMObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadXMProcessVM()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// XMProcessVMSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XMProcessVMSpecs struct {
	XMProcessVMProgramSpecs
	XMProcessVMMapSpecs
}

// XMProcessVMSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XMProcessVMProgramSpecs struct {
	XmProcessVmDoBrkFlags *ebpf.ProgramSpec `ebpf:"xm_process_vm_do_brk_flags"`
	XmProcessVmDoMmap     *ebpf.ProgramSpec `ebpf:"xm_process_vm_do_mmap"`
}

// XMProcessVMMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XMProcessVMMapSpecs struct {
	XmPvmEventRingbufMap *ebpf.MapSpec `ebpf:"xm_pvm_event_ringbuf_map"`
}

// XMProcessVMObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadXMProcessVMObjects or ebpf.CollectionSpec.LoadAndAssign.
type XMProcessVMObjects struct {
	XMProcessVMPrograms
	XMProcessVMMaps
}

func (o *XMProcessVMObjects) Close() error {
	return _XMProcessVMClose(
		&o.XMProcessVMPrograms,
		&o.XMProcessVMMaps,
	)
}

// XMProcessVMMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadXMProcessVMObjects or ebpf.CollectionSpec.LoadAndAssign.
type XMProcessVMMaps struct {
	XmPvmEventRingbufMap *ebpf.Map `ebpf:"xm_pvm_event_ringbuf_map"`
}

func (m *XMProcessVMMaps) Close() error {
	return _XMProcessVMClose(
		m.XmPvmEventRingbufMap,
	)
}

// XMProcessVMPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadXMProcessVMObjects or ebpf.CollectionSpec.LoadAndAssign.
type XMProcessVMPrograms struct {
	XmProcessVmDoBrkFlags *ebpf.Program `ebpf:"xm_process_vm_do_brk_flags"`
	XmProcessVmDoMmap     *ebpf.Program `ebpf:"xm_process_vm_do_mmap"`
}

func (p *XMProcessVMPrograms) Close() error {
	return _XMProcessVMClose(
		p.XmProcessVmDoBrkFlags,
		p.XmProcessVmDoMmap,
	)
}

func _XMProcessVMClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xmprocessvm_bpfeb.o
var _XMProcessVMBytes []byte
