net:
  port:
    pprof: 30001
    api: 31080
  ip:
    # 地址赋值类型：default_route, ip, itf_name
    assignType: default_route
    value: 0.0.0.0
api:
  path:
    metric: "/metrics"
eBPF:
  enabled: true
  modules:
    - name: cachestat
      enabled: false
      gather_interval: 5 # 收集kernel prog数据时间间隔，单位秒
    - name: oomkill
      enabled: false
    - name: runqlatency
      enabled: true
      gather_interval: 5
      conditions:
        histogram_scope: os # pidns

