resource:
  limits:
    memory: 2147483648 # 2G
    process_count: 32
    symbol_table_count: 384
net:
  port:
    pprof: 30001
    api: 31080
  ip:
    # 地址赋值类型：default_route, ip, itf_name
    assign_type: default_route
    value: 0.0.0.0
  pyroscope: "http://127.0.0.1:4040/"
api:
  path:
    metric: "/metrics"
eBPF:
  enabled: true
  programs:
    - name: cachestat
      enabled: true
      args:
        private:
          gather_interval: 5 # 收集 kernel prog 数据时间间隔，单位秒
    - name: cpusched
      enabled: true
      args:
        private:
          gather_interval: 5 # 收集 kernel prog 数据时间间隔，单位秒
        metrcs:
          - runq_latency
          - offcpu_duration
          - hang_process
        ebpf_prog:
          filter_scope_type: 1 # 1: os, 2: namespace, 4: PID, 5: PGID
          filter_scope_value: 0
          offcpu_min_millsecs: 5000 # 单位：毫秒
          offcpu_max_millsecs: 50000 #
          offcpu_task_type: 1 # 0: all, 1: user, 2: kernel
        exclude_comms:
        include_comms:
          - "xm_vm_test"
          - "x-monitor"
          - "x-monitor.eBPF"
          - "prometheus"
          - "top"
          - "pmlogger"
          - "irqbalance"
          - "systemd-journal"
          - "test_offcpu.sh"
          - "curl"
          - "python3"
          - "dd"
          - "fio"
    - name: processvm
      enabled: true
      args:
        metrcs:
          - privanon_share_pages
        private:
          object_count: 10 # gather_interval 时间内虚拟地址扩张最大的进程对象
        ebpf_prog:
          filter_scope_type: 1 # 1: os, 2: namespace, 4: PID, 5: PGID
          filter_scope_value: 0
        include_comms:
          - "xm_vm_test"
          - "x-monitor"
          - "x-monitor.ebpf"
          - "prometheus"
          - "top"
          - "pmlogger"
          - "irqbalance"
          - "systemd-journal"
        exclude_comms:
    - name: oomkill
      enabled: true
    - name: bio
      enabled: true
      args:
        ebpf_prog:
          filter_per_cmd_flag: true
          request_min_latency_millsecs: 10 # 单位：毫秒
          is_old_api: true # rhel8.5 是老 api，8.6 是新 api，可是 kernel version 相同
    - name: profile
      enabled: true
      args:
        private:
          gather_interval: 5 # 收集 kernel prog 数据时间间隔，单位秒
          sample_rate: 97
          targets:
            - name: "xmonitor" # 指标名称
              match: "MatchTargetComm" # 匹配应用程序名
              val: "x-monitor"
              labels: #自定义 label
                - l_name: "app"
                  l_val: "x-monitor"
            #- name: "grafana"
            #  match: "MatchTargetPidNS" # 匹配 pid namespace
            #  val: "4026532197"
            #  labels:
            #    - l_name: "app"
            #      l_val: "grafana"
            - name: "xmonitorebpf"
              match: "MatchTargetComm" # 匹配 匹配应用程序名
              val: "x-monitor.ebpf"
              labels:
                - l_name: "app"
                  l_val: "x-monitor.ebpf"
            #- name: "pyroscope"
            #  match: "MatchTargetPidNS" # 匹配 pid namespace
            #  val: "4026532259"
            #  labels:
            #    - l_name: "app"
            #      l_val: "pyroscope"
        ebpf_prog:
          filter_scope_type: 1 # 1: os, 2: namespace, 4: PID, 5: PGID
          filter_scope_value: 0
    - name: nfs
      enabled: true
      args:
        private:
          gather_interval: 5 # 收集 kernel prog 数据时间间隔，单位秒
