net:
  port:
    pprof: 30001
    api: 31080
  ip:
    # 地址赋值类型：default_route, ip, itf_name
    assignType: default_route
    value: 0.0.0.0
api:
  path:
    metric: "/metrics"
eBPF:
  enabled: true
  programs:
    - name: cachestat
      enabled: true
      gather_interval: 3 # 收集kernel prog数据时间间隔，单位秒
    #- name: oomkill
    #  enabled: false
    #- name: runqlatency
    #  enabled: false
    #  gather_interval: 3
    #  prog_rodata:
    #    filter_scope_type: 1 # 1: os，2：namespace，4：PID，5：PGID
    #    filter_scope_value: 0
    - name: cpusched
      enabled: true
      gather_interval: 3 # 单位：秒
      prog_rodata:
        filter_scope_type: 1 # 1: os，2：namespace，4：PID，5：PGID
        filter_scope_value: 0
        offcpu_threshold_millsecs: 1000 # 单位：毫秒
        offcpu_task_type: 1 # 0: all，1：user，2：kernel
      metrcs:
        - runq_latency_usecs
        - offcpu_over_time
        - hang_process


