net:
  port:
    pprof: 30001
    api: 31080
  ip:
    # 地址赋值类型：default_route, ip, itf_name
    assignType: default_route
    value: 0.0.0.0
api:
  path:
    metric: "/metrics"
eBPF:
  enabled: true
  programs:
    - name: cachestat
      enabled: false
      gather_interval: 3 # 收集kernel prog数据时间间隔，单位秒
    - name: cpusched
      enabled: false
      gather_interval: 3 # 单位：秒
      metrcs:
        - runq_latency
        - offcpu_duration
        - hang_process
      filter:
        prog_rodata:
          filter_scope_type: 1 # 1: os，2：namespace，4：PID，5：PGID
          filter_scope_value: 0
          offcpu_min_millsecs: 3000 # 单位：毫秒
          offcpu_max_millsecs: 50000 #
          offcpu_task_type: 1 # 0: all，1：user，2：kernel
        exclude_comms:
        include_comms:
          - "xm_vm_test"
          - "x-monitor"
          - "x-monitor.eBPF"
          - "prometheus"
          - "top"
          - "pmlogger"
          - "irqbalance"
          - "systemd-journal"
          - "test_offcpu.sh"
    - name: processvm
      enabled: false
      metrcs:
        - privanon_share_pages
      filter:
        object_count: 10 # gather_interval时间内虚拟地址扩张最大的进程对象
        prog_rodata:
          filter_scope_type: 1 # 1: os，2：namespace，4：PID，5：PGID
          filter_scope_value: 0
        include_comms:
          - "xm_vm_test"
          - "x-monitor"
          - "x-monitor.eBPF"
          - "prometheus"
          - "top"
          - "pmlogger"
          - "irqbalance"
          - "systemd-journal"
        exclude_comms:
    - name: oomkill
      enabled: true
    - name: bio
      enabled: true
      filter:
        prog_rodata:
          filter_per_cmd_flag: false
