net:
  port:
    pprof: 30001
    api: 31080
  ip:
    # 地址赋值类型：default_route, ip, itf_name
    assignType: default_route
    value: 0.0.0.0
api:
  path:
    metric: "/metrics"
eBPF:
  enabled: true
  programs:
    - name: cachestat
      enabled: false
      gather_interval: 3 # 收集kernel prog数据时间间隔，单位秒
    - name: oomkill
      enabled: false
    - name: runqlatency
      enabled: true
      gather_interval: 3
      conditions:
        filter_resource_type: 1 # 1: os，2：namespace，4：PID，5：PGID
        filter_resource_value: 0
