// Code generated by "stringer -type=GatherObjectType -output=gatherobjecttype_string.go"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GatherNone-0]
	_ = x[GatherOS-1]
	_ = x[GatherNamespace-2]
	_ = x[GatherCgroup-3]
	_ = x[GatherPID-4]
	_ = x[GatherPGID-5]
}

const _GatherObjectType_name = "GatherNoneGatherOSGatherNamespaceGatherCgroupGatherPIDGatherPGID"

var _GatherObjectType_index = [...]uint8{0, 10, 18, 33, 45, 54, 64}

func (i GatherObjectType) String() string {
	if i < 0 || i >= GatherObjectType(len(_GatherObjectType_index)-1) {
		return "GatherObjectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GatherObjectType_name[_GatherObjectType_index[i]:_GatherObjectType_index[i+1]]
}
