// Code generated by "stringer -type=SchedObjAttrType -output=schedobjattrtype_string.go"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ResAttrNone-0]
	_ = x[ResAttrOS-1]
	_ = x[ResAttrNamespace-2]
	_ = x[ResAttrCgroup-3]
	_ = x[ResAttrPID-4]
	_ = x[ResAttrPGID-5]
}

const _SchedObjAttrType_name = "ResAttrNoneResAttrOSResAttrNamespaceResAttrCgroupResAttrPIDResAttrPGID"

var _SchedObjAttrType_index = [...]uint8{0, 11, 20, 36, 49, 59, 70}

func (i SchedObjAttrType) String() string {
	if i < 0 || i >= SchedObjAttrType(len(_SchedObjAttrType_index)-1) {
		return "SchedObjAttrType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SchedObjAttrType_name[_SchedObjAttrType_index[i]:_SchedObjAttrType_index[i+1]]
}
